name: Create Github Release

on: 
  pull_request_target:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    name: Create Release

    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Echo github obj
        run: 'echo "payload: ${{ toJson(github.event) }}"'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false